params:
  color: black          # Any color in CSS syntax
  width: 60rem          # Any length in CSS syntax
  footer: >-            # A hardcoded space is needed before each html element
    obscure vision
  rss: To subscribe to this RSS feed, copy its address and paste it into your
    favorite feed reader.
  summaries: true       # Set to true to show summaries of posts on homepage
  divider: \a0          # Set to false to remove divider below posts on homepage
  utterances:
    repo:               # Set to Utterances repo URL to add Utterances comments
    issueterm: pathname
    theme: github-light

menu:
  nav:
  - name: about
    url: about/
    weight: 1
  - name: posts
    url: posts/
    weight: 2
  - name: tags
    url: tags/
    weight: 3
  - name: categories
    url: categories/
    weight: 4
  - name: rss
    url: index.xml
    weight: 5
